server:
  port: 8881

spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


  datasource:
    url: jdbc:h2:file:./db/database
    driverClassName: org.h2.Driver
    username: sa
    password: password

#logging:
#  level:
#    web: debug
#    root: debug